name: Generate preview and push it as latest

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'media/images/latest.png'

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Check installation of chrome headless
      run: sudo apt-get install -y chromium-browser
    - name: Start a preview generation
      run: chrome --headless=new --screenshot --window-size=360,760 https://gry-s.github.io/planning.html
    - name: Updates the screenshot.png
      run: mv screenshot.png media/images/latest.png
    - uses: actions/checkout@v3
    - name: Commit report
      run: |
        git config --global user.name 'Lpu8er'
        git config --global user.email 'lpu8er@users.noreply.github.com'
        git commit -am "Automated report"
        git push
